version: '3'

volumes:
  food_pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - food_pg_data:/var/lib/postgresql/data
  
  backend:
    image: sergeikrm/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/media/ 
    depends_on:
      - db
  
  frontend:
    image: sergeikrm/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  gateway:
    image: sergeikrm/foodgram_gateway
    env_file: .env
    volumes:
      - static:/staticfiles/
      - media:/media/  
    ports:
      - 8000:80
