# Generated by Django 3.2.3 on 2023-09-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0005_auto_20230920_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(related_name='recipes', through='foodgram.TagRecipe', to='foodgram.Tag'),
        ),
    ]
