# Generated by Django 3.2.3 on 2023-10-02 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0007_remove_recipe_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='amount',
        ),
    ]
