# Generated by Django 4.1 on 2023-10-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0015_recipe_pub_date_alter_ingredient_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_user_author',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='unique_user_author', violation_error_message='Вы уже подписаны на этого пользователя'),
        ),
    ]
