# Generated by Django 4.1 on 2023-10-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0016_remove_follow_unique_user_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_user_author',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='unique_user_author', violation_error_message='Вы уже подписаны на этого пользователя!'),
        ),
    ]
