# Generated by Django 4.1 on 2023-10-13 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0017_alter_recipe_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
    ]
