# Generated by Django 4.1 on 2023-10-13 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0018_alter_recipe_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
    ]
