# Generated by Django 4.1 on 2023-10-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0019_alter_recipe_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=0, upload_to='foodgram/images/', verbose_name='Картинка, закодированная в Base64'),
            preserve_default=False,
        ),
    ]
